title:  Recent Trends in Computer Algebra 2023
name: 
description: 
show_downloads: true
google_analytics:
theme: 

assets:
  sources:
    - assets/
    - assets/js
    - assets/css
    - assets/images
    - assets/images/logos


 
