title:  Recent Trends in Computer Algebra 2023
name: 
description: 
show_downloads: true
google_analytics: 

logo_url: "http://rtca2023.github.io"

 
bostan: <a href="https://specfun.inria.fr/bostan"> A. Bostan</a>
brisebarre: <a href="https://perso.ens-lyon.fr/nicolas.brisebarre/"> N. Brisebarre</a>
giesbrecht: <a href="https://cs.uwaterloo.ca/~mwg"> M. Giesbrecht</a>
koutschan: <a href="http://www.koutschan.de"> C. Koutschan</a>
mahboubi: <a href="http://people.rennes.inria.fr/Assia.Mahboubi/"> A. Mahboubi</a>
pous: <a href="http://perso.ens-lyon.fr/damien.pous/"> D. Pous</a>
safey: <a href="https://www-polsys.lip6.fr/~safey/"> M. Safey El Din</a>
salvy: <a href="http://perso.ens-lyon.fr/bruno.salvy"> B. Salvy</a>
schost: <a href="https://cs.uwaterloo.ca/~eschost/"> E. Schost</a>
villard: <a href="https://perso.ens-lyon.fr/gilles.villard/"> G. Villard</a>
