title:  Recent Trends in Computer Algebra 2023
name: 
description: 
show_downloads: true
google_analytics: 

logo_url: "http://rtca2023.github.io"

 
bostan: <a href="https://specfun.inria.fr/bostan"> A. Bostan</a>
giesbrecht: <a href="https://cs.uwaterloo.ca/~mwg"> M. Giesbrecht</a>
salvy: <a href="http://perso.ens-lyon.fr/bruno.salvy"> B. Salvy</a>
koutschan: <a href="http://www.koutschan.de"> C. Koutschan</a>